config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'sessions#new'
  get 'sessions/new'
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  get 'sign_out'  => 'sessions#destroy'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_secure_password

  # Validations
  validates :name, presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }
  VALID_EMAIL_FORMAT = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i # regex
  validates :email, presence: true, length: { maximum: 260 }, format: { with: VALID_EMAIL_FORMAT }, uniqueness: { case_sensitive: false }
  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    include SessionsHelper

    # autorization
    def authorize
      unless logged_in?
        redirect_to root_url
      end
   end

   def correct_user?
    @user = User.find(params[:id])
                unless current_user == @user
                           redirect_to users_path
                end
              end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_access, except: [:destroy]
    def create
              @user = User.find_by(email: params[:session][:email].downcase)
              if @user && @user.authenticate(params[:session][:password])
                          sign_in(@user)
              redirect_to @user
      else
              render 'new'
      end
    end

    def destroy
      sign_out
redirect_to root_url
end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]
  before_action :correct_user?, only: [:edit, :update, :destroy]
def index
@users = User.all  # @users is an instance variable that will be available to the view (index) and all other views in this
end
  def show
  @user = User.find(params[:id])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    sign_out
    redirect_to root_path, status: :see_other
  end


  private
  def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in (user)
    session[:user_id] = user.id
end
def current_user
    @current_user ||= User.find_by(id: session[:user_id])
end
def block_access
    if current_user.present?
               redirect_to users_path
    end
end

def logged_in?
  !current_user.nil?
  end

def sign_out
  session.delete(:user_id)
  @current_user = nil
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
    <div>
      <nav>
        <ul>
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li>
              <ul>
                <li><%= link_to "Profile", current_user %></li>
                 <li><%= link_to "Settings", edit_user_path(current_user) %></li> 

                <li>
                 <%= link_to 'Sign Out', sign_out_path, method: :delete %>

                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", root_path %></li>
             
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LojaDeLivros</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email %>
            </div>
            <div class="field">
                        <%= f.label :password %>
                        <%= f.password_field :password %>
            </div>
            <div class="field">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions">
                        <%= f.submit "Cadastrar"%>
            </div>
<% end %>

app/views/users/edit.html.erb
<h1>User Settings</h1>
<%= render 'form' %>

<ul>
            <li><%= link_to "Edit", edit_user_path(current_user) %></li>
            <li><%= link_to "Delete", @user, method: :delete%></li>
</ul>

app/views/users/index.html.erb
<h1> Users </h1>
 <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to "Show", user %></td>
        </tr>
     <%end%>
   </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<html>
              <body>
                          <h3> Perfil de <%= @user.name %> </h3>
                          <%= @user.email %>
                          <% if current_user == @user %>
                                     <ul>
                                                 <li><%= link_to "Edit", edit_user_path(current_user) %></li>
                                                 <li><%= link_to "Delete", @user, method: :delete%></li>
                                     </ul>
                          <%end%>
              </body>
  </html>